"""risk_budget_control_plane"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "7216a16dfb8d"
down_revision = "f27ae10b2928"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_slos",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "history_datasets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_calibrations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("data_epoch", sa.BigInteger(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_calibrations_source"), "risk_calibrations", ["source"], unique=False
    )
    op.create_table(
        "policy_candidates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("slo_id", sa.String(length=64), nullable=False),
        sa.Column("calibration_id", sa.String(length=64), nullable=False),
        sa.Column("base_revision", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("data_epoch", sa.BigInteger(), nullable=False),
        sa.Column("feasible", sa.Boolean(), nullable=False),
        sa.Column("frontier", sa.Boolean(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_digest", sa.String(length=64), nullable=False),
        sa.Column("optimizer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["risk_calibrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slo_id"],
            ["business_slos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policy_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("slo_id", sa.String(length=64), nullable=False),
        sa.Column("calibration_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=True),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["risk_calibrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["policy_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slo_id"],
            ["business_slos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action_history",
        sa.Column("id", sa.String(length=140), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=True),
        sa.Column("revision_id", sa.String(length=64), nullable=True),
        sa.Column("customer_id", sa.String(length=100), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=False),
        sa.Column("action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("expected_loss_cents", sa.Integer(), nullable=False),
        sa.Column("review_latency_seconds", sa.Float(), nullable=True),
        sa.Column("receipt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("postcondition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["history_datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["policy_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_history_action_id"), "action_history", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_history_arrived_at"), "action_history", ["arrived_at"], unique=False
    )
    op.create_index(
        op.f("ix_action_history_dataset_id"), "action_history", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_action_history_run_id"), "action_history", ["run_id"], unique=False)
    op.create_index(op.f("ix_action_history_tool"), "action_history", ["tool"], unique=False)
    op.create_table(
        "control_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slo_id", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.String(length=64), nullable=False),
        sa.Column("data_epoch", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["policy_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slo_id"],
            ["business_slos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policy_releases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.String(length=64), nullable=False),
        sa.Column("principal", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("diff_digest", sa.String(length=64), nullable=False),
        sa.Column("slo_digest", sa.String(length=64), nullable=False),
        sa.Column("calibration_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["policy_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id"),
    )
    op.create_table(
        "business_outcomes",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("history_id", sa.String(length=140), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("realized_loss_cents", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("observer", sa.String(length=100), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["history_id"],
            ["action_history.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_outcomes_history_id"), "business_outcomes", ["history_id"], unique=False
    )
    op.create_index(
        "one_final_outcome",
        "business_outcomes",
        ["history_id"],
        unique=True,
        postgresql_where=sa.text("outcome != 'unknown'"),
    )
    op.alter_column("agent_events", "run_id", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.execute("""CREATE FUNCTION safeops_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'immutable audit snapshot'; END $$""")
    for table in (
        "business_slos",
        "risk_calibrations",
        "policy_candidates",
        "policy_revisions",
        "policy_releases",
        "business_outcomes",
        "history_datasets",
    ):
        op.execute(
            f"CREATE TRIGGER immutable_snapshot BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION safeops_immutable()"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM agent_events WHERE run_id IS NULL")
    op.alter_column("agent_events", "run_id", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_index(
        "one_final_outcome",
        table_name="business_outcomes",
        postgresql_where=sa.text("outcome != 'unknown'"),
    )
    op.drop_index(op.f("ix_business_outcomes_history_id"), table_name="business_outcomes")
    op.drop_table("business_outcomes")
    op.drop_table("policy_releases")
    op.drop_table("control_state")
    op.drop_index(op.f("ix_action_history_tool"), table_name="action_history")
    op.drop_index(op.f("ix_action_history_run_id"), table_name="action_history")
    op.drop_index(op.f("ix_action_history_dataset_id"), table_name="action_history")
    op.drop_index(op.f("ix_action_history_arrived_at"), table_name="action_history")
    op.drop_index(op.f("ix_action_history_action_id"), table_name="action_history")
    op.drop_table("action_history")
    op.drop_table("policy_revisions")
    op.drop_table("policy_candidates")
    op.drop_index(op.f("ix_risk_calibrations_source"), table_name="risk_calibrations")
    op.drop_table("risk_calibrations")
    op.drop_table("history_datasets")
    op.drop_table("business_slos")
    op.execute("DROP FUNCTION safeops_immutable()")
    # ### end Alembic commands ###
