"""link_calibration_provenance"""

from alembic import op
import sqlalchemy as sa

revision = "ec11ec3b5c44"
down_revision = "7216a16dfb8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "candidate_base_revision",
        "policy_candidates",
        "policy_revisions",
        ["base_revision"],
        ["id"],
        use_alter=True,
    )
    op.add_column("risk_calibrations", sa.Column("dataset_id", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_risk_calibrations_dataset_id"), "risk_calibrations", ["dataset_id"], unique=False
    )
    op.create_foreign_key(None, "risk_calibrations", "history_datasets", ["dataset_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("risk_calibrations_dataset_id_fkey", "risk_calibrations", type_="foreignkey")
    op.drop_index(op.f("ix_risk_calibrations_dataset_id"), table_name="risk_calibrations")
    op.drop_column("risk_calibrations", "dataset_id")
    op.drop_constraint("candidate_base_revision", "policy_candidates", type_="foreignkey")
    # ### end Alembic commands ###
